acme_image_homepage:
    pattern:  /presets
    defaults: { _controller: AcmeImageBundle:Preset:index }
new_preset:
    pattern:  /presets/new
    defaults: { _controller: AcmeImageBundle:Preset:new }
update_preset:
    pattern:  /presets/{id}
    defaults: { _controller: AcmeImageBundle:Preset:update }
destroy_preset:
    pattern:  /presets/{id}/delete
    defaults: { _controller: AcmeImageBundle:Preset:destroy }
test_route:
    pattern: /yo/test
    defaults: { _controller: AcmeImageBundle:Preset:test }
ajax_update_mydata:
  pattern:  /update/data/from/ajax/call
  defaults: { _controller: AcmeImageBundle:MyAjax:updateData }
show_preset:
    pattern:  /presets/{id}/show
    defaults: { _controller: AcmeImageBundle:Preset:show }