Acme\ImageBundle\Entity\Preset2:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 10
        mode:
            - NotBlank: ~
            - Choice: [IN, OUT, EXACT]